env: "prod"

database:
  host: "db"
  port: 5432
  databaseName: "todo"
  user: "todo_manager"
  password: "1488"

http_server:
  address: "0.0.0.0:8069"
  timeout: 5s
  iddle_timeout: 60s

cors:
  addresses:
    - "http://localhost:4200"
    - "http://localhost:3000"
    - "http://localhost:8088"
    - "http://localhost:8069"